export const metadata = { title: 'Terms & Conditions | Sunny Texts' };
export default function TermsPage() {
  return <section className="page-hero"><div className="container legal">
    <h1>Sunny Texts Terms of Service</h1><p>Effective Date: August 10, 2025</p>
    <p>These Terms of Service (“Terms”) govern your use of Sunny Texts. By using our service, you agree to these Terms.</p>
    <h2>1. Service Description</h2><p>Sunny Texts provides a friendly AI-powered messaging companion via SMS. Our service is for entertainment, companionship, and informational purposes only. It is not a substitute for medical, legal, or financial advice.</p>
    <h2>2. Eligibility</h2><p>You must be at least 18 years old to use Sunny Texts.</p>
    <h2>3. Account & Subscription</h2><p>You agree to provide accurate information when signing up. Subscriptions are billed through Stripe after any free trial period. You may cancel anytime through your account or by contacting us.</p>
    <h2>4. Messaging Consent</h2><p>By signing up, you consent to receive recurring text messages. Message frequency varies. Message and data rates may apply. Reply STOP to cancel, HELP for help. Your consent is not a condition of purchase.</p>
    <h2>5. Acceptable Use</h2><p>You agree not to use Sunny Texts for sending spam, abusive, or unlawful messages or attempting to interfere with or disrupt our service.</p>
    <h2>6. AI Content</h2><p>Responses are generated by AI through OpenAI and may not always be accurate. You are responsible for how you use any information provided.</p>
    <h2>7. Data & Privacy</h2><p>We collect and use your data as described in our Privacy Policy.</p>
    <h2>8. Service Availability</h2><p>We may modify, suspend, or discontinue the service at any time without liability.</p>
    <h2>9. Limitation of Liability</h2><p>To the fullest extent permitted by Tennessee law, Sunny Texts is not liable for any damages arising from use of our service.</p>
    <h2>10. Governing Law</h2><p>These Terms are governed by the laws of the State of Tennessee, without regard to conflict of law principles.</p>
    <h2>11. Contact Us</h2><p>Email: sunny@sunnytexts.com<br />Call/Text: (855) 463-6694</p>
  </div></section>;
}
